### ISSUE TITLE
Provide generator for statements

### ISSUE THREAD

**Issue by elfring** [PyCQA/astroid#1229]
[Nodes are offered by this programming interface](https://docs.python.org/3/library/ast.html#ast.NodeVisitor "Visiting nodes").
They should also be provided for further data processing by [the means of a generator](https://docs.python.org/3/glossary.html#term-generator "Documentation").
The relevant items should be restricted to statements.

**Comment by Pierre-Sassoulas** [comment]
My guess is that ``I would like to achieve some collateral evolution also for assignment statements (for example).`` is just a pretentious/florished way of saying ``I also want generators for assignment statements`` (I guess class inheriting from ``mixins.AssignTypeMixin, Statement``, but at this point it's just a wild guess). Honestly I'm pretty fed up with deciphering and guessing whatever it is that you want from us, @elfring .  We know about generators, and code refactoring the issue is the way you communicate. Keep your communication simple and be respectful of our time, 

Also, It seems you're trying to push really hard for Coccinelle and computer science subjects that are perpendicular to astroid's core principle of being based on the python AST. Let me stop you right there. This project is not some kind of theoretical playground where you can make yourself feel good by talking about concept that would take (us) years to implements. Especially if it's only cryptic talk about it, without telling us what would be the advantages for the project and without trying to understand why the project is doing thing the way it does first.

**Comment by elfring** [comment]
>… is just a pretentious/florished way of saying `I also want generators for assignment statements` …

Assignments are just one kind of statements.
Selected statements should occasionally be analysed for further data processing.


>This project is not some kind of theoretical playground …

:thought_balloon: I hope still that information can be reused from various practical development experiences.


>… without telling us what would be the advantages …

Would you find the usage of generators more succinct than the specification of detailed loops (for data determination)?

**Comment by Pierre-Sassoulas** [comment]
> Assignments are just one kind of statements.

If you're talking about "ALL statements", the issue title already clear about that ? Yeah we know that there's different kind of statement. This does not bring any information.

> Selected statements should occasionally be analysed for further data processing.

There is no information at all in this sentence. None. None at all.  It actually make the kind of statements we're talking about LESS clear, and does not say anything about what processing we should do.  The issue title ``Provide generator for statements`` is actually clearer because at least we know it's generators we're talking about.

Honestly I'm done with this nonsense, I don't know if we're getting trolled or if you're acting in good faith, either way this ends now. If this is a machine learning research to do a real world Turing test this is hugely unethical.
