### ISSUE TITLE
Easy create nodes without having to call postinit()

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1346]
### Current behavior

We need to call the `postinit` method on every new node that has children in order to set node's field. From someone coming from standard library ast, this is rather annoying since all arguments can be passed to the constructor in the standard library. 

### Proposed change

I've created this class that makes it more simple to create `NodeNG` instances. Tell me if you'de like it to be part of astroid, I can send a PR. This really helps a lot when migrating code that creates simple `ast` nodes to `astroid`.

```python
class _NodeFactory:
    """
    Easy create NodeNG instances. 

    Acts like every node arguments can be passed to the constructor method and calls `postinit` automatically with the required value.
    """

    def __create_node(self, node_type: Type[astroid.nodes.NodeNG], *args: Any, **kwargs: Any) -> astroid.nodes.NodeNG:
        sig = inspect.signature(node_type.__init__)
        init_args = args
        init_kwargs = {}
        for name in sig.parameters.keys():
            if name in kwargs:
                init_kwargs[name] = kwargs.pop(name)
        node = node_type(*init_args, **init_kwargs)
        if hasattr(node, 'postinit') and len(kwargs)>0:
            node.postinit(**kwargs)

        return node

    def __getattr__(self, name: str) -> Callable[[Any], astroid.nodes.NodeNG]:
        if not name in astroid.nodes.__dict__:
            raise AttributeError("unknown node {!r}".format(name))
        node_type = astroid.nodes.__dict__[name]
        assert issubclass(node_type, astroid.nodes.NodeNG), "not a node type {!r}".format(name)
        return functools.partial(self.__create_node, node_type)

nodefactory = _NodeFactory()
"""
Acts like every node arguments can be passed to the constructor method. 
"""
```

Then we can use something like:
```python
nodefactory.Subscript(value=nodefactory.Name(name=name),
                                 slice=slice)
```

Tell me what you think, thanks.

**Comment by Pierre-Sassoulas** [comment]
I also dislike ``postinit`` but I don't understand why it was made like this in the first place which is a bad sign when you're going for a refactor.

**Comment by DanielNoord** [comment]
I think the reason for doing is because of how the `parent` attribute works.
If we create a `FunctionDef` and `Arguments` there is a bit of a chicken and egg problem: `FunctionDef` needs the `Arguments` to be initialised so it can be added as `args` attribute, whereas `Arguments` needs `FunctionDef` for its `parent` attribute.

There are probably better ways around doing this, but I just thought I'd explain why I think the initial decision to do this like this was made. Perhaps there is even a hacky way of creating a builder that calls `init` and `postinit` at the same time like in your suggestion @tristanlatr, but I think we should indeed be careful with changes to this system.

**Comment by tristanlatr** [comment]
I don't want to change the system, just provide a simpler way to create simple node class. 

We can add a warning saying that some functions of astroid might not work as expected on node created with the factory. 

I'm using this factory class to create nodes like `Const`, `Name`, `Tuple`, `Attribute`, `Subscript`, and other stuff present in type annotations. I'm not "creating a builder".

We can also create a function like `fix_missing_parent()` that could populated the `parent`attribute, it the issue is only with the parent attribute.

I'm just proposing this to make it simpler for users to transition from python ast to astroid.

**Comment by DanielNoord** [comment]
Hmm, I'm not sure if we should add such a helper function if we can't be sure that it handles all node types and their specificities. That will probably only create issues about "Why doesn't this factory helper work..." etc. Seeing the limited maintainer time we have for this project I don't think we should expose ourselves to that. If we put it in, we have to maintain it..

**Comment by cdce8p** [comment]
I agree with @DanielNoord. Although I don't like `postinit` myself it's a necessity to resolve the cycle with the parent attribute. I once though about removing it myself, by assigning `parents` after the whole tree is created, but that didn't work out the way it was supposed to. Even if it had, it would have been a massive breaking change. Not worth it IMO.

Regarding the particular helper function. We should add something like this if it only works in certain cases. Furthermore, on another issue there was a discussion about `inspect.signature`. Turns out this is quite an time expensive function. We should try to avoid it as much as possible.

Overall, I think the status quo is good enough and anything else would just be to disruptive.
