### ISSUE TITLE
Deprecate `doc` attribute?

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/astroid#1414]
With the new addition of `doc_node` (#1276), should the "old" `doc` attribute be deprecated and later removed?

/CC: @DanielNoord

**Comment by DanielNoord** [comment]
Yeah, I don't see a reason to keep it. It only adds unnecessary overhead and attributes. I'm +1.

Do we want to deprecate in `2.11` as well?

**Comment by cdce8p** [comment]
> Do we want to deprecate in `2.11` as well?

It would make sense IMO 🤔 Need to see if I have the time to work on a PR later today.

**Comment by DanielNoord** [comment]
@cdce8p If you want I can make a PR for this so you only have to review. That should take you less time (depending on the quality of my PR 😄)

**Comment by cdce8p** [comment]
> @cdce8p If you want I can make a PR for this so you only have to review. That should take you less time (depending on the quality of my PR 😄)

Go for it! I did start working on it but haven't had the time to finish it. You're welcome to use my changes if you find them useful. Just know that there might still be some bugs. https://github.com/PyCQA/astroid/compare/main...cdce8p:deprecate-doc

**Comment by DanielNoord** [comment]
Copied from https://github.com/PyCQA/astroid/pull/1432#pullrequestreview-898319366:

What I have mind
- [ ] Update `Module`, `ClassDef`, `FunctionDef`.
  1.1 The `doc` attribute in `__init__` should be optional with default. Required if we later want to remove it from existing calls.
  1.2 Property and property setter method for `doc` with DeprecationWarning
-> https://github.com/PyCQA/astroid/pull/1434
- [ ] Update other (similar) classes, mainly `object.Property` and `PartialFunction`, with similar changes if necessary.
-> https://github.com/PyCQA/astroid/pull/1436
-> https://github.com/PyCQA/astroid/pull/1437
- [ ] Update code base, to remove the `doc` attribute where it's passed to `__init__` and replace it with `doc_node` to `postinit`. Also update functions which could handle an optional doc_node instead of a string -> `AsStringVisitor`.
- [ ] Add decorator to deprecate `doc` attribute from `__init__` calls.
- [ ] ... Did I miss something 🤔  ... _probably_
- [ ] Update all attribute calls to `.doc` if not already done. `ClassModel.attr___doc__`, `AsStringVisitor._docs_dedent`, ...

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I think the work on `doc` is nearing its conclusion.

Perhaps we can get #1450 in `2.11` as well, but I suggest moving all other issues to the `2.12` milestone. None of the open issues are particularly pressing for `pylint` and the release of `astroid` kind of is.

**Comment by DanielNoord** [comment]
WIth https://github.com/PyCQA/astroid/runs/5486844569?check_suite_focus=true passing on `main` without any `DeprecationWarnings` for `doc` being raised I guess the work here is done 😄

**Comment by cdce8p** [comment]
Thanks for the help @DanielNoord 🚀
