### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stratakis** [PyCQA/astroid#377]
Hi,

Is it possible to make a new release?

As it seems there hasn't been a new release for a long time and currently 557 commits are on top of 1.4.8 release.

**Comment by PCManticore** [comment]
Not currently. At this moment, astroid==1.5.0 and pylint==2.0.0 are using a lot of new features, some of them being a bit unstable, there are some issues to fix before committing to a release. But more important than this is that pylint==2.0.0 is not ready yet, there are some improvements scheduled for it, but there is a slow progress towards achieving this thing, since I don't have a lot of time on my hands lately. Once we manage to complete the issues that are in the 2.0 milestone, we can proceed with a release. Unfortunately, the current astroid master has to wait for pylint==2.0.0, because otherwise, astroid 1.5.0== will be incompatible with pylint==1.7.0 for example.

Another solution that we did in the past was to cherry-pick a lot of relevant changes from master branch into a separate release branch and do the release from there. I've been doing this twice and I am not going there again. This time both master branches will be released at the same time.
