### ISSUE TITLE
Layered DictUnpack nodes become uninferable

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#483]
### Steps to reproduce
```python
import astroid
code = """
base = {'data': 0}
new = {**base, 'data': 1}
new3 = {**base, **new}
b = new3 #@
"""
ass = astroid.extract_node(code)
ass.value.inferred()
```

### Current behavior

The above code returns `[Uninferable]`

### Expected behavior

return `[Dict]`

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.0.0

**Comment by PCManticore** [comment]
Note that the following can be inferred:
```
import astroid
code = """
base = {'data': 0}
new = {'data': 1}
new3 = {**base, **new}
new3 #@
"""
ass = astroid.extract_node(code)
print(ass.inferred())
```
The only difference is that it does not have the first `**base` inside the `new` dictionary. This suggest to me that this would be caused by the inference context, with which we can't re-fetch the same data that was already inferred once for `**base`. If you can try to remove the `context` from `_infer_map` in `inference.py` and see if it works, that would be great, as it would provide some additional clues on why this is not working.

**Comment by brycepg** [comment]
Removing the context from `_infer_map` does fix this issue. I'll try to figure out where the `Uninferable` originates from.

**Comment by PCManticore** [comment]
Yes, that's true, we have a bunch of problems with InferenceContext, here's the relevant issue in which you might be interested: https://github.com/PyCQA/astroid/issues/108
