### ISSUE TITLE
Reconsider the usefulness of Unknown

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#523]
Pylint is failing on `pandas` because of `Unknown` not having a name attribute.
```
    def visit_call(self, node):
        """Visit a Call node."""
        try:
            for inferred in node.func.infer():
                if inferred is astroid.Uninferable:
                    continue
>               if inferred.root().name == OPEN_MODULE:
E               AttributeError: 'Unknown' object has no attribute 'name'

../pylint/pylint/checkers/stdlib.py:209: AttributeError
```

**Comment by brycepg** [comment]
Also qname() too

```
  File "/home/user/pylint/pylint/checkers/refactoring.py", line 661, in _is_function_def_never_returning
    return node.qname() in self._never_returning_functions
AttributeError: 'Unknown' object has no attribute 'qname'
```

**Comment by PCManticore** [comment]
This makes sense for now, but if I remember correctly, my intention was for `Unknown` to not leak outside of `astroid`. Unfortunately I never got around to fix this, but maybe we can reuse this issue to get to that point. One reason for why we'd want to do this is because `Unknown` doesn't actually have any value by itself, and users are already used to `Uninferable`. By handling `Unknown` outside of astroid, we'd raise the extra cases that the users should account for to 3:
- one for Uninferable
- another one for catching `InferenceError` when inferring
- and another one to verify that the node is `Unknown`
At the same time, sometimes having it is required/useful. For instance we won't have an alternative if we were to drop it from the `elts` of inferred sequences. We *know* there is a node there, but we just can't infer it. It would be wrong to just not add it, since this will mean that the length of the `elts` will vary and so on.

**Comment by brycepg** [comment]
I'm going to close this because `Unknown` is important for unknown nodes, `Uninferable` is needed to show partial inference failure
