### ISSUE TITLE
Inference error linting django

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#533]
### Steps to reproduce
1. Download django 2.0.4: https://github.com/django/django/archive/2.0.4.zip
2. unzip, cd to directory
3. run `pylint django/template/context.py`

### Current behavior

Fails with an exception

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/pylint/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/home/user/pylint/pylint/__init__.py", line 18, in run_pylint
    Run(sys.argv[1:])
  File "/home/user/pylint/pylint/lint.py", line 1359, in __init__
    linter.check(args)
  File "/home/user/pylint/pylint/lint.py", line 779, in check
    self._do_check(files_or_modules)
  File "/home/user/pylint/pylint/lint.py", line 912, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/user/pylint/pylint/lint.py", line 992, in check_astroid_module
    walker.walk(ast_node)
  File "/home/user/pylint/pylint/utils.py", line 1036, in walk
    self.walk(child)
  File "/home/user/pylint/pylint/utils.py", line 1036, in walk
    self.walk(child)
  File "/home/user/pylint/pylint/utils.py", line 1036, in walk
    self.walk(child)
  File "/home/user/pylint/pylint/utils.py", line 1033, in walk
    cb(astroid)
  File "/home/user/pylint/pylint/checkers/stdlib.py", line 236, in visit_call
    self._check_shallow_copy_environ(node)
  File "/home/user/pylint/pylint/checkers/stdlib.py", line 208, in _check_shallow_copy_environ
    if inferred.qname() == OS_ENVIRON:
AttributeError: 'Super' object has no attribute 'qname'
```

### Expected behavior

No exception

### Discussion

Should inference be leaking `Super` nodes? Should we add `qname` for Non-scoped nodes (to `NodeNG`) (empty string or a series of names like `mymod.myclass.myfunc.mysuper`) ? or should this code be changed to have a guard conditional?

### Version

astroid commit: 5d77795885879572a3f0e9779f0ac88789f1d267
pylint commit: 164933412f685c407616866537fb16caecaef066
Python 3.6.4

**Comment by PCManticore** [comment]
Inference shouldn't probably leak `Super` so we should look into that. Regarding `qname` I think it's fine as we have it right now, only for scoped nodes.

**Comment by ceridwen** [comment]
It is possible to return a super object in Python code:
```
class C:
   def foo(self): return super()
```

This returns `<super: <class 'C'>, <C object>>`.  I don't know *why* you'd ever want to do this, but given this is Python someone has probably done it.  If the inference can't return Super, what should it return for the above code?

**Comment by PCManticore** [comment]
That's a good point @ceridwen From my point of view, I was considering `Super` to be more of an internal object to astroid's inference engine, but you are right that there is no placeholder for it in some cases such as the one you mentioned, e.g when we just pass `super()` from one point to another.
Given this, it might make sense to have an empty string `qname()` for non-scoped nodes. Does that sounds good for you as well, Bryce? I'm afraid otherwise we'd have to guard almost every place in pylint where we use `qname()`.

**Comment by brycepg** [comment]
@PCManticore Yeah that sounds actionable. I didn't realize is `super()` is an object after being called. I think the string should be `super` instead of an empty string because `type(super()).__qualname__` and `super.__qualname__` is `super`.

**Comment by justinfx** [comment]
Is it possible to cherry-pick this in to the 1.6 version stream and cut a 1.6.7? We are still porting from python2 to 3 and as far as I know (unless something has recently changed) we can only use python2 to perform `pylint --py3k` checking across python2 and 3 source code because of some pylint parser logic.
