### ISSUE TITLE
Should Inference infer all elements of a list?

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#564]
### Steps to reproduce
Given the following code, inference does not evaluate the elts of the list:
```python
import astroid
code = """
def foo():
    return 1
x = list([foo()])
x
"""
node = astroid.extract_node(code)
node.inferred()[0].as_string()
```
### Current behavior
The above code returns `'[foo()]'`

### Expected behavior

Return `[1]` by evaluating elts.

### version
cdd9756b0f9ac270a2ca365ecde972d47a891e94

**Comment by PCManticore** [comment]
This is a good question, I'm not exactly sure what's best. What if the function call from the list has multiple potential values, say can be inferred as both a string and a integer, what would be stash inside the list? All the inferred elements of the said function call? That's why it's a bit easier now, as you only have to iterate through the elements of the list and call `.infer()` appropriately.

**Comment by brycepg** [comment]
Yeah I think you're right. There also could be performance problems otherwise if astroid made a list for each possible inference outcome or tried to infer each value of a long list.
