### ISSUE TITLE
Understanding the scope of type inference

### ISSUE THREAD

**Issue by pmiddend** [PyCQA/astroid#642]
Sorry for reaching out this way, but I didn't find any "contact information".

I want to write a pylint checker that tests `if` statements that check for a redundant `None`. So

```
a: int
if a is None:
  pass
```

will result in a message "redundant check for `None`", whereas

```
a: Optional[int]
if a is None:
  pass
```

will pass the test.

Given an `If(...)`, I'd need the type for the `left` expression. This doesn't seem to be generally possible with astroid. At least `.infer(...)` always gives me `Uninferable`. Am I overlooking something here, or is inference just not there yet?

**Comment by PCManticore** [comment]
Hi @pmiddend 
In your example you are getting an `Uninferable` because the code is a bit nonsensical. `a` does not have a value per se, it only has an annotation, which means that the inference engine cannot assign anything to it other than an object that indicates that the inference failed.
If you want to grab the type of `a`, you'd have to resort to scope lookup followed by an actual inspection of the annotation, or something along these lines:

```
from astroid import extract_node
n = extract_node('''
from typing import Optional
a: Optional[int]
if a is None: #@
  pass
''')
print(n.test.left.inferred()) # Uninferable
print(n.previous_sibling()) # Gives you the AnnAssign node
print(n.previous_sibling().target) # Gives you the `AssignName` corresponding to that annotation
print(n.scope().lookup('a')[1][0].parent) # Gives you again the `AnnAssign` node but via a lookup instead of grabbing the previous sibling
```
