### ISSUE TITLE
Add numpy brain tips for `numpy.append`

### ISSUE THREAD

**Issue by willsALMANJ** [PyCQA/astroid#666]
### Steps to reproduce
astroid currently does not account for `numpy.append` as mentioned in #664. An example of the problem is the following file:

```
import numpy as np
a = np.append([0], 0)
a = -a
```

which produces the following errors in pylint:

```
/tmp/test.py:3:4: E1130: bad operand type for unary -: tuple (invalid-unary-operand-type)
/tmp/test.py:3:4: E1130: bad operand type for unary -: list (invalid-unary-operand-type)
```

These errors are generated for pylint=1.7.2, astroid=1.5.3 and numpy=1.16.2. The errors are not generated for numpy=1.15.4.

**Comment by hippo91** [comment]
Thanks for the bug report @willsALMANJ. 
The problems comes from the fact that the `append` function is not correctly inferred as a `numpy.ndarray`. 
I'll try to add a brain for this function ASAP.

**Comment by hippo91** [comment]
@willsALMANJ just a few words to explain why your issue is not yet solved.
There is no need to add the function `append` into a `numpy brain` as this function is defined inside a standard python module inside `numpy`. The problem arises when `astroid` tries to infer the result of the call to `append`. By analyzing the source, `astroid` is aware that the result of `append` comes from the call to `numpy`'s `concatenate` function. This function is defined inside the `brain_numpy_core_multiarray` `astroid` module and so should be correctly inferred.
I'am still investigating.
