### ISSUE TITLE
Update six version

### ISSUE THREAD

**Issue by uilianries** [PyCQA/astroid#718]
### Steps to reproduce
1. pip install -U six
2. pip install astroid

### Current behavior
    ERROR: astroid 2.3.2 has requirement six==1.12, but you'll have six 1.13.0 which is incompatible.

**Comment by verhulstm** [comment]
I found the exact same issue

**Comment by akuzminsky** [comment]
it should be ` "six~=1.12",`, IMO.

**Comment by tseader** [comment]
I discovered this issue as well as it causes problems within `pytest-pylint` pip install.

**Comment by verhulstm** [comment]
do we have a work around for this?

**Comment by uilianries** [comment]
> do we have a work around for this?

Yes, install first six==1.12.0:

    pip install six==1.12.0
    pip install -r requirements.txt

**Comment by tseader** [comment]
> > do we have a work around for this?
> 
> Yes, install first six==1.12.0:
> 
> ```
> pip install six==1.12.0
> pip install -r requirements.txt
> ```

Did the same thing independently and can confirm that works.  Note that it did not work to include six first or last within requirements.txt for me.

**Comment by barrywhart** [comment]
It would be cool to include a lower but not upper bound on `six`, or at least an upper bound only in the major version number (`1`), not the major and minor (`1.12`). The current approach makes `astroid` very difficult to use in conjunction with other packages, which often have requirements like `six>=1.13`. Since `pylint` depends on `astroid`, this introduces potential version conflicts in every project I work on (since they all use `pylint`.)

**Comment by hippo91** [comment]
@barrywhart  in `astroid` we require only `~=1.12` which, from what i can read in PEP440, is equivalent to `>= 1.12, == 1.*`

**Comment by barrywhart** [comment]
We had the issue with pip-compile, a tool which tries to choose a set of compatible versions before installing anything, and it was rejecting use of 1.13. Maybe a bug in pip-compile, though, because updating to the latest pip-compile no longer reported an incompatibility. Thanks#
