### ISSUE TITLE
Question about brain tips for third-party libs

### ISSUE THREAD

**Issue by gyermolenko** [PyCQA/astroid#720]
Hi.

Seems like `astroid` maintains brain tips for some third-party libraries like `numpy`, `pytest` , `responses` and many others.
There are some related github/Issues in pylint/astroid in regard to what they could/couldn't infer from some third-party modules.

It looks like responsibility for corresponding plugin, to have such tips?
Or maybe I'm missing something. Could you please clarify?

Thanks.

**Comment by PCManticore** [comment]
Hi @gyermolenko We maintain these on `astroid` side as we're the most familiar on how they should be written in order to help `pylint`. Hopefully sometime in the future we'll be able to parse `.pyi` files and grab third party related information from stub files, but until then we have to rely on astroid transform to help `pylint` figure out certain uninferable concepts, such as dynamic aspects of Python (e.g. modules that rely on `globals` or descriptors etc)
