### ISSUE TITLE
Regression in astroid-2.4: False positive not-callable error

### ISSUE THREAD

**Issue by hiranya911** [PyCQA/astroid#775]
We are using Pylint 2.3.1. Until today following class linted without issues:

```
class PageIterator:
    def __init__(self, current_page):
        # Removed for clarity

    def next(self):
        # Removed for clarity

    def __next__(self):
        return self.next()

    def __iter__(self):
        return self
```

Today since astroid-2.4.0 was released, our CI workflows are failing with the following error:

```
E1102: self.next is not callable (not-callable)
```

Line number points to the `return self.next()` in the above class. This seems to be a regression as this used to work fine, and `self.next()` is clearly a callable member method of the class.

Note that we are still using the same version of Pylint as before (it is hardcoded into our build scripts). But Astroid version is not controlled, and hence the CI workflow seems to pick the latest available.

**Comment by PCManticore** [comment]
Thanks for the report. Unfortunately I cannot reproduce it using the released version. Here's what I'm getting:
```
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)
a.py:1:0: C0115: Missing class docstring (missing-class-docstring)
a.py:5:4: C0116: Missing function or method docstring (missing-function-docstring)
```
I tried with pylint 2.4.4 and astroid 2.4.0 as well and got the same output.

Also you should probably either downgrade `astroid` or upgrade `pylint` to 2.5.0, since this `astroid` release might be incompatible with the previous `pylint` version.

If you happen to reproduce this on your side, please reopen the issue with more details.
