### ISSUE TITLE
Debian astroid 2.4.2: ExceptionModelTest.test_oserror

### ISSUE THREAD

**Issue by sandrotosi** [PyCQA/astroid#798]
Hello,
while preparing 2.4.1 for inclusion in Debian, the test suite generated this failure:

```
_______________________ ExceptionModelTest.test_oserror ________________________

self = <tests.unittest_object_model.ExceptionModelTest testMethod=test_oserror>

    def test_oserror(self):
        ast_nodes = builder.extract_node(
            """
        try:
            raise OSError("a")
        except OSError as err:
           err.filename #@
           err.filename2 #@
           err.errno #@
        """
        )
        expected_values = ["", "", 0]
        for node, value in zip(ast_nodes, expected_values):
            inferred = next(node.infer())
>           assert isinstance(inferred, astroid.Const)
E           AssertionError: assert False
E            +  where False = isinstance(Uninferable, <class 'astroid.node_classes.Const'>)
E            +    where <class 'astroid.node_classes.Const'> = astroid.Const

tests/unittest_object_model.py:586: AssertionError
=== 1 failed, 880 passed, 35 skipped, 14 xfailed, 1 xpassed in 10.17 seconds ===
```

**Comment by sandrotosi** [comment]
@PCManticore any idea if someone can look into this? it's still failing on a debian system as of v2.4.2

**Comment by keichi** [comment]
It's still failing in astroid 2.8.4 (running on Ubuntu 20.04 and Python 3.8.10). Hopefully someone could look into it.

**Comment by keichi** [comment]
I've figured out this test fails when the `six` package is installed. More specifically, it fails when the test `tests/unittest_brain.py::SixBrainTest::test_attribute_access` runs before it.

The root cause seems [this](https://github.com/python/cpython/blob/v3.8.10/Lib/shutil.py#L630) line in `shutil` (`shutil` is indirectly imported from `brain_six.py`: `brain_six.py` -> `urllib.error` -> `urllib.response` -> `tempfile` -> `shutil`). If this line is removed, the test passes. Hope this helps with debugging this issue.

**Comment by Pierre-Sassoulas** [comment]
It does help a lot ! We just need to skip the test if six is installed (we do this elsewhere already). Do you want to fix this yourself as you did all the hard work ?
